encoding: UTF-8
# GitHub
username: egg-plant
repo: egg-plant.github.io
branch: master

source: .
destination: _site

# Setup
title: Egg Plants Ramblings'
tagline: A fun insight into the world of Maths, Computer Science and Programming.
description: egg plant is a fun dude with some great knowledge to share.
url: http://stanko.github.io
baseurl: ''
future: true
Time Zone: Europe/London
paginate: 5
